name: conditions
on:
  push:
    branches:
      - main
      - feature/login
  pull_request: 
    branches:
      - feature/login
  workflow_dispatch:

    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      #- name: simulate failuer
      #  run: exit 1

     # - name: failure message
        #if: ${{failure()}}
        #run: echo "Test job failed"
        
      - name: print testing
        run: echo "Testing"

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: print build message
        run: echo "Building application"
  deploy:
    needs:
      - build
    if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        run: echo "Deploying to production"

      






        
