name: Laravel CI
on:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: install composer denpendencies
        run: composer install --no-interaction --prefer-dist

      - name: create .env file
        run: mv .env.example .env

      - name: generate app key
        run: php artisan key:generate

      - name: check code formatting
        run: vendor/bin/pint --test

      - name: Run laravel test
        run: echo "database setup is required for this test"
